# Generated by Django 4.0.3 on 2022-08-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_year', models.CharField(max_length=5, null=True)),
                ('produca_image', models.ImageField(upload_to='producats')),
            ],
        ),
        migrations.CreateModel(
            name='Bagpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_year', models.CharField(max_length=5, null=True)),
                ('produca_image', models.ImageField(upload_to='producats')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_year', models.CharField(max_length=5, null=True)),
                ('produca_image', models.ImageField(upload_to='producats')),
            ],
        ),
        migrations.CreateModel(
            name='Mans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_year', models.CharField(max_length=5, null=True)),
                ('produca_image', models.ImageField(upload_to='producats')),
            ],
        ),
        migrations.CreateModel(
            name='ProducatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Womans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_year', models.CharField(max_length=5, null=True)),
                ('produca_image', models.ImageField(upload_to='producats')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('deprition', models.TextField()),
                ('produca_image_1', models.ImageField(default='default.jpg', upload_to='producats')),
                ('produca_image_2', models.ImageField(default='default.jpg', upload_to='producats')),
                ('produca_image_3', models.ImageField(default='default.jpg', upload_to='producats')),
                ('produca_image_4', models.ImageField(default='default.jpg', upload_to='producats')),
                ('produca_image_5', models.ImageField(default='default.jpg', upload_to='producats')),
                ('is_stock', models.BooleanField(default=True)),
                ('is_discount', models.IntegerField(default=0)),
                ('producat_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catagory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producatstatus')),
            ],
        ),
    ]
